/**
 * cdc_capture — real-life Change Data Capture via a source-side trigger + outbox.
 *
 * Watermark polling (`WHERE updated_at > x`) cannot see DELETEs and misses updates
 * on tables without an update-timestamp. To keep an ES/hub copy correct for FULL
 * row-level CRUD — inserts, updates, AND deletes — we use the standard trigger+outbox
 * pattern (what Debezium does with the WAL, done here with a trigger since we don't
 * tap the log):
 *
 *   • An `AFTER INSERT OR UPDATE OR DELETE` trigger on the source table writes one row
 *     per change — `(seq, op, pk, doc, ts)` — into a change-log ("outbox") table.
 *   • `seq` is a monotonic sequence (bigserial / AUTO_INCREMENT): the reliable, ordered
 *     watermark. A poller drains `WHERE seq > lastSeq ORDER BY seq` and applies
 *     I/U as upserts and **D as deletes** to the destination, advancing `lastSeq`.
 *
 * Engines: PostgreSQL (single trigger, `to_jsonb`) and MySQL (3 triggers, `JSON_OBJECT`).
 * Requires write access to the source to install the trigger + outbox (one-time).
 */

/** One captured change from the outbox. */
export interface ChangeRow { seq: number; op: 'I' | 'U' | 'D'; pk: string; doc: any; }

const idq_pg = (s: string) => '"' + String(s).replace(/"/g, '') + '"';
const idq_my = (s: string) => '`' + String(s).replace(/`/g, '') + '`';
/** Sanitize to a safe identifier fragment for the outbox object names. */
const safe = (s: string) => String(s).replace(/[^a-zA-Z0-9_]/g, '_');

export class CdcCapture {
  /** Outbox table/function/trigger names for a source table (kept short + safe). */
  private static names(schema: string, table: string) {
    const base = `${safe(schema)}_${safe(table)}`;
    return { base, pgLog: `${base}_chg`, pgFn: `${base}_cdc_fn`, pgTrg: `${base}_cdc`, myLog: `fabric_cdc_${base}_chg` };
  }

  /**
   * Install the change-capture trigger + outbox for a source table (idempotent).
   * @param engine source engine ('POSTGRES' | 'MYSQL').
   * @param conn source connector (must expose `rawQuery`).
   * @param schema source schema/db.
   * @param table source table.
   * @param pk primary-key column (used as the change `pk`).
   * @param columns column names (needed to build MySQL's `JSON_OBJECT`).
   */
  static async ensure(engine: string, conn: any, schema: string, table: string, pk: string, columns: string[]): Promise<void> {
    const e = String(engine).toUpperCase();
    if (e === 'POSTGRES' || e === 'POSTGRESQL') return this.ensurePg(conn, schema, table, pk);
    if (e === 'MYSQL') return this.ensureMy(conn, schema, table, pk, columns);
    if (e === 'ORACLE' || e === 'ORACLEDB') return this.ensureOra(conn, schema, table, pk, columns);
    throw new Error(`CDC capture not yet supported for engine "${engine}" — use scheduled SYNC (full reload) or add a timestamp watermark. Postgres/MySQL/Oracle support trigger-based CDC; Snowflake via Streams (planned).`);
  }

  /** Oracle trigger + outbox (23c: IDENTITY seq, JSON_OBJECT payload, compound I/U/D predicates). */
  private static async ensureOra(conn: any, schema: string, table: string, pk: string, columns: string[]): Promise<void> {
    const n = this.names(schema, table);
    const oq = (s: string) => '"' + String(s).replace(/"/g, '').toUpperCase() + '"';
    const LOG = oq(n.myLog);        // reuse the safe base name (uppercased + quoted)
    const T = oq(table), P = oq(pk), TRG = oq(`${n.base}_cdc`);
    try {
      await conn.rawQuery(`CREATE TABLE ${LOG} (seq NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, op VARCHAR2(1), pk VARCHAR2(255), doc CLOB, ts TIMESTAMP DEFAULT SYSTIMESTAMP)`);
    } catch (e: any) { if (!/ORA-00955/.test(e.message)) throw e; /* already exists */ }
    const jsonObj = (ref: 'NEW' | 'OLD') => `JSON_OBJECT(${columns.map((c) => `'${c.replace(/'/g, '')}' VALUE :${ref}.${oq(c)}`).join(', ')})`;
    await conn.rawQuery(
      `CREATE OR REPLACE TRIGGER ${TRG} AFTER INSERT OR UPDATE OR DELETE ON ${T} FOR EACH ROW
       BEGIN
         IF DELETING THEN INSERT INTO ${LOG}(op, pk, doc) VALUES ('D', TO_CHAR(:OLD.${P}), ${jsonObj('OLD')});
         ELSIF UPDATING THEN INSERT INTO ${LOG}(op, pk, doc) VALUES ('U', TO_CHAR(:NEW.${P}), ${jsonObj('NEW')});
         ELSE INSERT INTO ${LOG}(op, pk, doc) VALUES ('I', TO_CHAR(:NEW.${P}), ${jsonObj('NEW')});
         END IF;
       END;`);
  }

  private static async ensurePg(conn: any, schema: string, table: string, pk: string): Promise<void> {
    const n = this.names(schema, table);
    const S = idq_pg(schema), T = idq_pg(table), P = idq_pg(pk);
    await conn.rawQuery(`CREATE SCHEMA IF NOT EXISTS fabric_cdc`);
    await conn.rawQuery(`CREATE TABLE IF NOT EXISTS fabric_cdc.${idq_pg(n.pgLog)} (
      seq bigserial PRIMARY KEY, op char(1) NOT NULL, pk text, doc jsonb, ts timestamptz DEFAULT now())`);
    await conn.rawQuery(`CREATE OR REPLACE FUNCTION fabric_cdc.${idq_pg(n.pgFn)}() RETURNS trigger LANGUAGE plpgsql AS $CDC$
      BEGIN
        IF (TG_OP = 'DELETE') THEN
          INSERT INTO fabric_cdc.${idq_pg(n.pgLog)}(op, pk, doc) VALUES ('D', (OLD.${P})::text, to_jsonb(OLD)); RETURN OLD;
        ELSIF (TG_OP = 'UPDATE') THEN
          INSERT INTO fabric_cdc.${idq_pg(n.pgLog)}(op, pk, doc) VALUES ('U', (NEW.${P})::text, to_jsonb(NEW)); RETURN NEW;
        ELSE
          INSERT INTO fabric_cdc.${idq_pg(n.pgLog)}(op, pk, doc) VALUES ('I', (NEW.${P})::text, to_jsonb(NEW)); RETURN NEW;
        END IF;
      END; $CDC$`);
    await conn.rawQuery(`DROP TRIGGER IF EXISTS ${idq_pg(n.pgTrg)} ON ${S}.${T}`);
    await conn.rawQuery(`CREATE TRIGGER ${idq_pg(n.pgTrg)} AFTER INSERT OR UPDATE OR DELETE ON ${S}.${T}
      FOR EACH ROW EXECUTE FUNCTION fabric_cdc.${idq_pg(n.pgFn)}()`);
  }

  private static async ensureMy(conn: any, schema: string, table: string, pk: string, columns: string[]): Promise<void> {
    const n = this.names(schema, table);
    const db = idq_my(schema), T = idq_my(table), P = idq_my(pk), LOG = idq_my(n.myLog);
    await conn.rawQuery(`USE ${db}`);
    await conn.rawQuery(`CREATE TABLE IF NOT EXISTS ${LOG} (
      seq BIGINT AUTO_INCREMENT PRIMARY KEY, op CHAR(1) NOT NULL, pk VARCHAR(255), doc JSON, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    const jsonObj = (ref: 'NEW' | 'OLD') => `JSON_OBJECT(${columns.map((c) => `'${c.replace(/'/g, '')}', ${ref}.${idq_my(c)}`).join(', ')})`;
    for (const [suffix, op, ev, ref] of [['i', 'I', 'INSERT', 'NEW'], ['u', 'U', 'UPDATE', 'NEW'], ['d', 'D', 'DELETE', 'OLD']] as const) {
      const trg = idq_my(`${n.base}_cdc_${suffix}`);
      await conn.rawQuery(`DROP TRIGGER IF EXISTS ${trg}`);
      await conn.rawQuery(`CREATE TRIGGER ${trg} AFTER ${ev} ON ${T} FOR EACH ROW
        INSERT INTO ${LOG}(op, pk, doc) VALUES ('${op}', ${ref}.${P}, ${jsonObj(ref as 'NEW' | 'OLD')})`);
    }
  }

  /** Current max outbox seq (the CDC "log position") — used to baseline after a snapshot. */
  static async maxSeq(engine: string, conn: any, schema: string, table: string): Promise<number> {
    const n = this.names(schema, table);
    const e = String(engine).toUpperCase();
    const oq = (s: string) => '"' + String(s).replace(/"/g, '').toUpperCase() + '"';
    try {
      if (e === 'MYSQL') { await conn.rawQuery(`USE ${idq_my(schema)}`); const r = await conn.rawQuery(`SELECT COALESCE(MAX(seq),0) AS m FROM ${idq_my(n.myLog)}`); return Number(r?.[0]?.m || 0); }
      if (e === 'ORACLE' || e === 'ORACLEDB') { const r = await conn.rawQuery(`SELECT NVL(MAX(seq),0) AS "m" FROM ${oq(n.myLog)}`); return Number(r?.[0]?.m ?? r?.[0]?.M ?? 0); }
      const r = await conn.rawQuery(`SELECT COALESCE(MAX(seq),0) AS m FROM fabric_cdc.${idq_pg(n.pgLog)}`); return Number(r?.[0]?.m || 0);
    } catch { return 0; }
  }

  /** Read a batch of changes with `seq > sinceSeq`, oldest first. */
  static async read(engine: string, conn: any, schema: string, table: string, sinceSeq: number, limit: number): Promise<ChangeRow[]> {
    const n = this.names(schema, table);
    const e = String(engine).toUpperCase();
    const oq = (s: string) => '"' + String(s).replace(/"/g, '').toUpperCase() + '"';
    let rows: any[];
    if (e === 'MYSQL') {
      await conn.rawQuery(`USE ${idq_my(schema)}`);
      rows = await conn.rawQuery(`SELECT seq, op, pk, doc FROM ${idq_my(n.myLog)} WHERE seq > ? ORDER BY seq ASC LIMIT ${Math.floor(limit)}`, [sinceSeq]);
    } else if (e === 'ORACLE' || e === 'ORACLEDB') {
      rows = await conn.rawQuery(`SELECT seq AS "seq", op AS "op", pk AS "pk", doc AS "doc" FROM ${oq(n.myLog)} WHERE seq > :1 ORDER BY seq ASC FETCH FIRST ${Math.floor(limit)} ROWS ONLY`, [sinceSeq]);
    } else {
      rows = await conn.rawQuery(`SELECT seq, op, pk, doc FROM fabric_cdc.${idq_pg(n.pgLog)} WHERE seq > $1 ORDER BY seq ASC LIMIT ${Math.floor(limit)}`, [sinceSeq]);
    }
    return (rows || []).map((r: any) => ({
      seq: Number(r.seq ?? r.SEQ), op: (r.op ?? r.OP) as 'I' | 'U' | 'D', pk: r.pk ?? r.PK,
      doc: typeof (r.doc ?? r.DOC) === 'string' ? JSON.parse(r.doc ?? r.DOC) : (r.doc ?? r.DOC),
    }));
  }

  /** Prune applied outbox rows up to and including `upToSeq` (keeps the log bounded). */
  static async prune(engine: string, conn: any, schema: string, table: string, upToSeq: number): Promise<void> {
    const n = this.names(schema, table);
    const e = String(engine).toUpperCase();
    const oq = (s: string) => '"' + String(s).replace(/"/g, '').toUpperCase() + '"';
    try {
      if (e === 'MYSQL') { await conn.rawQuery(`USE ${idq_my(schema)}`); await conn.rawQuery(`DELETE FROM ${idq_my(n.myLog)} WHERE seq <= ?`, [upToSeq]); }
      else if (e === 'ORACLE' || e === 'ORACLEDB') await conn.rawQuery(`DELETE FROM ${oq(n.myLog)} WHERE seq <= :1`, [upToSeq]);
      else await conn.rawQuery(`DELETE FROM fabric_cdc.${idq_pg(n.pgLog)} WHERE seq <= $1`, [upToSeq]);
    } catch { /* pruning is best-effort */ }
  }
}
